# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
remote_theme: "mmistakes/so-simple-theme@3.2.0"
skin: "/assets/css/skins/default.css"
locale: en-US
title: "leewc"
description: "A blog on programming, software development and thoughts."
baseurl: # the subpath of your site, e.g. "/blog"
url: https://leewc.com
logo: /images/meow.jpg
date_format: "%B %-d, %Y"
read_time: true
words_per_minute: 180
mathjax: true
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: UA-64050901-1
disqus:
  shortname: leewc
twitter:
  username: wenchuanlee

# dangit, forgot why I added this here before the merge. :(
enforce_ssl: "leewc.com"

# Liquid
liquid:
  error_mode: strict

permalink:   /:categories/:title/
markdown:    kramdown
feed:
  path: atom.xml
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

# Pagination - https://jekyllrb.com/docs/pagination/
# paginate: 10
# paginate_path: /page:num/

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

# Search
search_full_content: false # can have performance implications for large sites

# Taxonomy pages
# category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true

# # Site Author
author:
  name: Wen Chuan Lee
#   picture:
#   email:
#   twitter:
#   links:
#     - title:
#       url:
#       icon:

# Footer Links
footer_links:
  - title: Twitter
    url: https://twitter.com/wenchuanlee
    icon: fab fa-twitter-square
  - title: LinkedIn
    url: https://linkedin.com/in/wenchuanlee
    icon: fab fa-linkedin-in
  - title: StackOverflow
    url: https://stackoverflow.com/users/4512948/matrixanomaly
    icon: fab fa-stack-overflow
  - title: GitHub
    url: https://github.com/leewc
    icon: fab fa-github-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square